---
include:
- project: tq-em/public/build/toolchain
  file: ci/apps.yml
  ref: main
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF == null

- project: tq-em/public/build/toolchain
  file: ci/apps.yml
  ref: $PUBLIC_TOOLCHAIN_CI_REF
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF

Prepare:
  extends: .prepare-app-build

Build Package (aarch64):
  extends: .build-aarch64-app

Go Linter:
  extends: .go-lint

Go Sec:
  extends: .go-sec

Unit Tests:
  stage: test
  extends:
    - .artifacts-always-one-week
    - .gitlab-runner-tag
    - .rule-skip-for-integration-tests
  script:
    - make go-test-junit
  after_script:
    - mkdir -p artifacts/tests/backend
    - mv report.xml artifacts/tests/backend/${ARTIFACT_REF}_unittests.xml
  coverage: '/total: \d+\.\d+/'
  artifacts:
    when: always
    paths:
      - artifacts/tests/backend/${ARTIFACT_REF}_unittests.xml
    reports:
      junit: artifacts/tests/backend/${ARTIFACT_REF}_unittests.xml


Yarn Audit:
  stage: test
  extends:
    - .gitlab-runner-tag
  script:
    - make yarn-audit

Gitleaks:
  extends: .gitleaks

Deploy Snapshot:
  extends: .deploy-snapshot
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      # TBD: Workaround for missing release deployment
    - if: $CI_COMMIT_TAG
