---
include:
- project: tq-em/public/build/toolchain
  file: ci/apps.yml
  ref: main
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF == null

- project: tq-em/public/build/toolchain
  file: ci/apps.yml
  ref: $PUBLIC_TOOLCHAIN_CI_REF
  rules:
    - if: $PUBLIC_TOOLCHAIN_CI_REF


Prepare:
  extends: .prepare-app-build

Build Package (aarch64):
  extends: .build-aarch64-app

Go Linter:
  extends: .go-lint

Go Sec:
  extends: .go-sec

Gitleaks:
  extends: .gitleaks

Deploy Snapshot:
  extends: .deploy-snapshot
