// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tq-systems/go-dbus/serial (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=modbus/mocks/serial/serial_mock.go -package=serialmock github.com/tq-systems/go-dbus/serial Client
//

// Package serialmock is a generated GoMock package.
package serialmock

import (
	reflect "reflect"

	serial "github.com/tq-systems/go-dbus/serial"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// BindInterface mocks base method.
func (m *MockClient) BindInterface(name string, config any, rebind bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindInterface", name, config, rebind)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindInterface indicates an expected call of BindInterface.
func (mr *MockClientMockRecorder) BindInterface(name, config, rebind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindInterface", reflect.TypeOf((*MockClient)(nil).BindInterface), name, config, rebind)
}

// GetInterface mocks base method.
func (m *MockClient) GetInterface(name string, config any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterface", name, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetInterface indicates an expected call of GetInterface.
func (mr *MockClientMockRecorder) GetInterface(name, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterface", reflect.TypeOf((*MockClient)(nil).GetInterface), name, config)
}

// GetInterfaceRaw mocks base method.
func (m *MockClient) GetInterfaceRaw(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterfaceRaw", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceRaw indicates an expected call of GetInterfaceRaw.
func (mr *MockClientMockRecorder) GetInterfaceRaw(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceRaw", reflect.TypeOf((*MockClient)(nil).GetInterfaceRaw), name)
}

// ListInterfaces mocks base method.
func (m *MockClient) ListInterfaces() (map[string]serial.BindState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInterfaces")
	ret0, _ := ret[0].(map[string]serial.BindState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaces indicates an expected call of ListInterfaces.
func (mr *MockClientMockRecorder) ListInterfaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaces", reflect.TypeOf((*MockClient)(nil).ListInterfaces))
}

// Reset mocks base method.
func (m *MockClient) Reset(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockClientMockRecorder) Reset(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockClient)(nil).Reset), name)
}

// SetOperState mocks base method.
func (m *MockClient) SetOperState(name string, state serial.OperState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOperState", name, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOperState indicates an expected call of SetOperState.
func (mr *MockClientMockRecorder) SetOperState(name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOperState", reflect.TypeOf((*MockClient)(nil).SetOperState), name, state)
}

// UnbindInterface mocks base method.
func (m *MockClient) UnbindInterface(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindInterface", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindInterface indicates an expected call of UnbindInterface.
func (mr *MockClientMockRecorder) UnbindInterface(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindInterface", reflect.TypeOf((*MockClient)(nil).UnbindInterface), name)
}
